import { NextResponse } from 'next/server';

export async function GET() {
    const services = [
        {
            id: 'srv_1',
            merchantId: 'merch_1',
            title: 'Haircut & Styling',
            description: 'Professional haircut and styling options',
            category: 'Hair',
            subCategory: 'Haircut',
            price: 85,
            currency: 'EUR',
            duration: 60,
            images: [],
            variants: [],
            isActive: true,
            isPopular: true,
            totalBookings: 154,
            averageRating: 4.8,
            totalReviews: 45,
            tags: ['hair', 'cut', 'style'],
            createdAt: '2024-01-01T00:00:00.000Z',
            updatedAt: '2024-01-01T00:00:00.000Z',
        },
        {
            id: 'srv_2',
            merchantId: 'merch_1',
            title: 'Manicure Deluxe',
            description: 'Complete nail care with premium polish',
            category: 'Nails',
            subCategory: 'Manicure',
            price: 45,
            currency: 'EUR',
            duration: 45,
            images: [],
            variants: [],
            isActive: true,
            isPopular: true,
            totalBookings: 89,
            averageRating: 4.9,
            totalReviews: 32,
            tags: ['nails', 'manicure'],
            createdAt: '2024-01-01T00:00:00.000Z',
            updatedAt: '2024-01-01T00:00:00.000Z',
        },
        {
            id: 'srv_3',
            merchantId: 'merch_1',
            title: 'Full Body Massage',
            description: 'Relaxing full body massage with essential oils',
            category: 'Massage',
            subCategory: 'Relaxation',
            price: 120,
            currency: 'EUR',
            duration: 90,
            images: [],
            variants: [],
            isActive: true,
            isPopular: false,
            totalBookings: 42,
            averageRating: 4.7,
            totalReviews: 14,
            tags: ['massage', 'relax'],
            createdAt: '2024-01-01T00:00:00.000Z',
            updatedAt: '2024-01-01T00:00:00.000Z',
        },
    ];

    return NextResponse.json({
        success: true,
        data: services,
        pagination: {
            currentPage: 1,
            totalPages: 1,
            totalItems: services.length,
            itemsPerPage: 10,
        },
    });
}
